on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  PYTHON_VERSION: '3.10'
  ALLURE_VERSION: '2.35.1'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip & Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path 'requirements.txt') {
            python -m pip install -r requirements.txt
          } else {
            Write-Host "requirements.txt not found, skipping"
          }
          python -m pip install allure-pytest pytest-html

      - name: Create directories
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path logs,allure-results,allure-report,report,site -Force | Out-Null

      - name: Run Pytest (produce Allure results + pytest HTML)
        shell: pwsh
        run: |
          python -m pytest tests/ `
            --alluredir=allure-results `
            --html=report/pytest-report.html `
            --self-contained-html `
            --maxfail=1 `
            --disable-warnings `
            --tb=short `
            -v

      - name: Install Allure CLI (Windows)
        shell: pwsh
        run: |
          $version = "${{ env.ALLURE_VERSION }}"
          $url = "https://github.com/allure-framework/allure2/releases/download/$version/allure-$version.zip"
          $zip = "$env:TEMP\allure-$version.zip"
          Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing
          Expand-Archive -Path $zip -DestinationPath allure -Force
          $allureHome = (Get-ChildItem -Path allure -Directory)[0].FullName
          $bin = Join-Path $allureHome 'bin'
          Add-Content -Path $env:GITHUB_ENV -Value "ALLURE_HOME=$allureHome"
          Add-Content -Path $env:GITHUB_ENV -Value "PATH=$bin;$env:PATH"

      - name: Generate Allure HTML report
        shell: pwsh
        run: |
          if ((Get-ChildItem -Path allure-results -Recurse -ErrorAction SilentlyContinue | Measure-Object).Count -eq 0) {
            Write-Host "No Allure results found. Skipping report generation."
            exit 0
          }
          & "$env:ALLURE_HOME\bin\allure.bat" generate allure-results -o allure-report --clean

      - name: Prepare site folder
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force site -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path site/allure-report,site/pytest-report -Force | Out-Null
          if (Test-Path allure-report) { Copy-Item -Recurse -Force allure-report/* site/allure-report/ }
          if (Test-Path report/pytest-report.html) { Copy-Item report/pytest-report.html site/pytest-report/index.html }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: |
            allure-report
            report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages